version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-saas-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
      - redis
    networks:
      - ci4-saas-network

  db:
    image: mysql:8.0
    container_name: ci4-saas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ci4_saas
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: ci4_user
      MYSQL_PASSWORD: ci4_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - ci4-saas-network

  redis:
    image: redis:7-alpine
    container_name: ci4-saas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci4-saas-network

  nginx:
    image: nginx:alpine
    container_name: ci4-saas-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - ci4-saas-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4-saas-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - ci4-saas-network

  mailhog:
    image: mailhog/mailhog
    container_name: ci4-saas-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ci4-saas-network

volumes:
  db_data:
  redis_data:

networks:
  ci4-saas-network:
    driver: bridge
